// Runtime consistency: the evaluator, the runtime and the scenario must state one result for one invocation.
import { decide, externalResult, type Actor, type Bindings, type Snapshot, type Value } from "./evaluate.js";
import { fitsType, INVOCATION_RESULTS, own, type Stage1Ontology, type Type } from "./expr.js";

/** A result as the runtime or a scenario states it. `reason` only for INVALID_BINDING. No `param`: runtimes do not report it. */
export type Reported = { result: string; reason?: "missing" | "unknown_param" | "type" | "not_found" };

export interface RuntimeCase {
  id: string; // invocation id, generated by the harness
  action: string;
  snapshot: Snapshot | null; // typed snapshot taken before the invocation
  inputs: { bindings: Bindings; actor: Actor; scope: string | null; now: number };
  reported: Reported | null; // what the runtime reported; null = not reported
  expected: Reported | null; // the scenario expectation; null = none
}

export type CannotReconcile = "envelope" | "runtime_missing" | "expectation_missing" | "snapshot_missing" | "evaluator_error" | "runtime_unmapped" | "indeterminate";

export type ReconcileRow =
  | { id: string; action: string; status: "match"; result: Reported }
  | { id: string; action: string; status: "mismatch"; evaluator: Reported; reported: Reported; expected: Reported }
  | { id: string; action: string; status: "cannot_reconcile"; reason: CannotReconcile; detail?: string };

/** Decodes one stored value of a property with a declared type; undefined = cannot decode. Never called with null. */
export type Decode = (raw: unknown, type: Type) => Value | undefined;
export type TypeDefect = { object: string; prop: string; row: string; value: unknown };

// Stored rows (physical values) -> a typed snapshot. Each property with a declared type is decoded and then checked with
// fitsType; a value that cannot be decoded or does not fit is a defect and keeps its raw value. Null is never decoded.
// An absent column is not projected (decide throws when it reads it: an incomplete snapshot). Pure link tables fail closed.
export function projectSnapshot(
  ont: Stage1Ontology,
  stores: Readonly<Record<string, readonly Readonly<Record<string, unknown>>[]>>,
  decode: Decode,
): { snapshot: Snapshot; defects: TypeDefect[] } {
  const datasources = new Set(Object.values(ont.objectTypes).map((o) => o.datasource));
  for (const l of ont.linkTypes) if (l.table !== undefined && !datasources.has(l.table)) throw new Error(`pure link ${l.id} is not projected`);
  const objects: Snapshot["objects"] = {};
  const defects: TypeDefect[] = [];
  for (const [object, o] of Object.entries(ont.objectTypes)) {
    if (!Object.hasOwn(stores, o.datasource)) throw new Error(`snapshot lacks store ${o.datasource}`);
    objects[object] = stores[o.datasource].map((stored) => {
      const row: Record<string, unknown> = { ...stored };
      for (const [prop, p] of Object.entries(o.properties)) {
        const raw = row[prop];
        if (p.type === undefined || raw === undefined || raw === null) continue;
        const v = decode(raw, p.type);
        if (v === undefined || !fitsType(v, p.type)) defects.push({ object, prop, row: String(row.id), value: raw });
        else row[prop] = v;
      }
      return row as Record<string, Value>;
    });
  }
  return { snapshot: { objects }, defects };
}

// Strict on reason: both absent is equal; INVALID_BINDING with different reasons is not.
const same = (a: Reported, b: Reported): boolean => a.result === b.result && a.reason === b.reason;
const ENVELOPE = ["REPLAYED", "IDEMPOTENCY_CONFLICT"];
const INVOCATION: readonly string[] = INVOCATION_RESULTS;

// The results a runtime may report for an action: the invocation results and the results its decision table gives.
function mapped(ont: Stage1Ontology, action: string, result: string): boolean {
  if (INVOCATION.includes(result)) return true;
  const decision = own(ont.actionTypes, action)?.decision;
  return (decision?.rows ?? []).some((r) => r.result === result) || decision?.otherwise?.result === result;
}

// One row per case, in input order. The evaluator result is computed only to compare: a missing runtime result or
// expectation is reported as such, never filled in from the decision table. Envelope results are not decisions (the
// evaluator does not implement the envelope; a replay does not recompute domain conditions), so decide is not called.
// A reported result that the action cannot give (runtime_unmapped) means the runtime did not report its domain result.
export function reconcile(ont: Stage1Ontology, cases: readonly RuntimeCase[]): ReconcileRow[] {
  return cases.map((c): ReconcileRow => {
    const head = { id: c.id, action: c.action };
    const cannot = (reason: CannotReconcile, detail?: string): ReconcileRow => ({ ...head, status: "cannot_reconcile", reason, ...(detail !== undefined ? { detail } : {}) });
    const { reported, expected, snapshot } = c;
    if (reported === null) return cannot("runtime_missing");
    if (ENVELOPE.includes(reported.result)) return cannot("envelope");
    if (expected === null) return cannot("expectation_missing");
    if (snapshot === null) return cannot("snapshot_missing");
    const { bindings, actor, scope, now } = c.inputs;
    let d: ReturnType<typeof decide>;
    try {
      d = decide(ont, c.action, snapshot, scope, bindings, actor, now);
    } catch (e) {
      return cannot("evaluator_error", e instanceof Error ? e.message : String(e));
    }
    if (!mapped(ont, c.action, reported.result)) return cannot("runtime_unmapped", reported.result);
    if (d.layer === "indeterminate") return cannot("indeterminate", d.reason);
    const { result, reason } = externalResult(d);
    const evaluator: Reported = reason !== undefined ? { result, reason } : { result };
    return same(evaluator, reported) && same(evaluator, expected) ? { ...head, status: "match", result: evaluator } : { ...head, status: "mismatch", evaluator, reported, expected };
  });
}
